CREATE TABLE system_res (
  id BIGINT NOT NULL AUTO_INCREMENT,
  pid BIGINT DEFAULT NULL,
  NAME VARCHAR(111) DEFAULT NULL,
   permission VARCHAR(100),
  url VARCHAR(255) DEFAULT NULL,
  seq INT(11) DEFAULT '1',		/*排序*/
  TYPE INT(1) DEFAULT '2' COMMENT '1 菜单 2 按钮',
   available INT DEFAULT 1 COMMENT '1 可用 0 不可用',
  des VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

CREATE TABLE system_role (
  id BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(55) DEFAULT NULL,
  seq INT(11) DEFAULT '1',
  pid INT(11) DEFAULT '0',
  des VARCHAR(55) DEFAULT NULL,
  available INT DEFAULT 1 COMMENT '1 可用 0 不可用',
  PRIMARY KEY (id)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

CREATE TABLE SYSTEM_USER
(
	id           BIGINT NOT NULL AUTO_INCREMENT,
	loginname    VARCHAR(100) NOT NULL,
	PASSWORD     VARCHAR(100) NOT NULL,
	salt VARCHAR(100),
	NAME         VARCHAR(100) NOT NULL,
	email        VARCHAR(100) NOT NULL,
	mobilephone          VARCHAR(11)							COMMENT '移动电话',
	loginCount          INT					DEFAULT 0		COMMENT '登录次数',
	lastLoginTime        DATETIME								COMMENT '最后登录时间',
	originalPic          VARCHAR(200)							COMMENT '头像',
	STATUS INT(1) DEFAULT '1' COMMENT '#1 不在线 2.封号状态 ',
	PRIMARY KEY (id)
)ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;



CREATE TABLE system_user_role (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT DEFAULT NULL,
  role_id BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FK_SYSTME_USER_ROLE_USER_ID (user_id),
  KEY FK_SYSTME_USER_ROLE_ROLE_ID (role_id),
  CONSTRAINT FK_SYSTME_USER_ROLE_ROLE_ID FOREIGN KEY (role_id) REFERENCES system_role (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_SYSTME_USER_ROLE_USER_ID FOREIGN KEY (user_id) REFERENCES SYSTEM_USER (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

CREATE TABLE system_role_res (
  id BIGINT NOT NULL AUTO_INCREMENT,
  res_id BIGINT DEFAULT NULL,
  role_id BIGINT DEFAULT NULL,
  PRIMARY KEY (id),
  KEY FK_SYSTEM_ROLE_RES_RES_ID (res_id),
  KEY FK_SYSTEM_ROLE_RES_ROLE_ID (role_id),
  CONSTRAINT FK_SYSTEM_ROLE_RES_RES_ID FOREIGN KEY (res_id) REFERENCES system_res (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_SYSTEM_ROLE_RES_ROLE_ID FOREIGN KEY (role_id) REFERENCES system_role (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;